apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ include "digdirator.fullname" . }}
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
    team: {{ .Values.team }}
spec:
  image: "{{ .Values.image.repository }}/{{ .Values.image.name}}:{{ .Values.image.tag}}"
  port: 8080
  strategy:
    type: Recreate
  replicas:
    min: {{.Values.digdirator.replicas.min}}
    max: {{.Values.digdirator.replicas.max}}
  liveness:
    path: /metrics
  readiness:
    path: /metrics
  prometheus:
    enabled: true
    path: /metrics
  envFrom:
    - secret: digdirator-env
  accessPolicy:
    inbound:
      rules:
        - application: prometheus
    outbound:
      external:
      {{- range .Values.digdirator.outbound.external }}
        - host: {{ . }}
      {{- end }}
      {{- if not .Values.digdirator.onprem.enabled }}
        - host: cloudkms.googleapis.com
        - host: secretmanager.googleapis.com
      {{- end }}
  {{- if .Values.digdirator.onprem.enabled }}
  webproxy: true
  env:
  {{- range $key,$value:= .Values.digdirator.env }}
    - name: "{{ $key}}"
      value: {{ $value | quote }}
  {{- end }}
  filesFrom:
    - secret: digdirator-google-service-account
      mountPath: "/var/run/secrets/google"
  {{- end }}
  skipCaBundle: true