apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-env
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.digdirator.secrets.environment | nindent 2 }}