apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-env
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.digdirator.secrets.environment | nindent 2 }}

{{- if .Values.digdirator.onprem.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-google-service-account
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
data:
  sa.json: |
    {{ .Values.digdirator.secrets.google.sa.credentials }}
{{ end }}