apiVersion: v2
name: digdirator
description: Helm Chart of a K8s cluster operator for automated registration and lifecycle management 
  of ID-porten and Maskinporten clients.
type: application
version: 0.0.3
appVersion: 0.0.1
