---
apiVersion: nais.io/v1
kind: MaskinportenClient
metadata:
  name: my-app
  namespace: aura
spec:
  secretName: my-secret
  scopes:
    exposes:
      - name: "digdirator.test.read"
        enabled: true
        atAgeMax: 114 # token expires in sec # default 30 sec
        # allowedIntegration: maskinporten # default maskinporten
        consumers:
          - name: "Some User"
            orgno: "889640782"
    use:
      - name: "nav:test/api"

# exposes
# new format -> nav:teamnamespace:appnavn.scope.read
# legacy format -> nav:some/api (applikasjons kan move to gcp, if they want to keep config in yml)