---
apiVersion: nais.io/v1
kind: MaskinportenClient
metadata:
  name: my-app
  namespace: myteam
spec:
  secretName: my-secret
  scopes:
    exposes:
      # nav:arbeid:digdirator.test.read
      - name: "digdirator.test.read"
        enabled: true
        product: "arbeid"
        consumers:
          - orgno: "889640782"
    consumes:
      - name: "nav:test/api"
