name: Build Dependabot PR

on: [pull_request_target]

env:
  image: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Checkout code and setup node
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: |
          docker build --pull --tag ${IMAGE} .