name: Build Dependabot PR

on: [pull_request]

jobs:
  build:
    name: Checkout code and setup node
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build .