name: Build and test PR

on: [pull_request]

jobs:
  build:
    name: Checkout code and setup node
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build .